Added Arr::from() and fromRecursive()
bolt/collection pull request #5
Opened 2017-08-03 07:54 UTC by CarsonF

`Arr::from()` normalizes iterables, null, and stdClass to arrays.
`Arr::fromRecursive()` does the same thing recursively (this was previously locked away in a private Bag method).

-----

[RFC] Bags, when normalizing collections, convert non-iterables to an array of one item. I didn't think that was appropriate for `Arr::from()`. And I'm wondering if that should be deprecated/immediately removed from Bags as well. It is a bit of an edge case and I don't think it even makes sense:
```php
$bag = new Bag(['blue']);
$bag->replace('red');
// bag is now ['red']
```

2017-08-03 08:12 UTC, GwendolenLynch approved these changes
If this had landed yesterday, you'd have saved me about 30 minutes of beating my head against a virtual brick wall of my own stupidity! :+1:

2017-08-03 08:26 UTC, GwendolenLynch requested changes
Marking for change, only as I missed the RFC and need to review and think though it.

2017-08-04 05:17 UTC, CarsonF commented
Ok I updated code to so Bags throw exception when given a non-iterable now for parameters accepting an iterable.

2017-08-04 05:26 UTC, GwendolenLynch approved these changes

2017-08-04 05:26 UTC, merged